server:
  port: 8089
jedis:
  database: 0
  zk:
    connect:
      host: zdbd01:2181,zdbd02:2181,zdbd03:2181
    session:
      timeout: 5000
    proxy:
      dir: /jodis/codis-test1
  session:
    auth: 123456
  connection:
    ##连接超时时间（毫秒）
    timeout: 2000
  sotimeout: 2000
  ##最大连接数
  maxTotal: 100
  ##连接池中的最大空闲连接
  maxIdle: 10
  ##连接池中的最小空闲连接
  minIdle: 10
  maxWaitMillis: 10000
  softMinEvictableIdleTimeMillis: 5000